services:
  - type: web
    name: iptv-proxy
    runtime: docker
    dockerfilePath: Dockerfile  # سننشئ هذا الملف أيضاً
    envVars:
      - key: M3U_URL_1
        value: "http://a9.lion.wine:80/live/1blu533468/Gxp61220/1277234.ts"  # ضع رابط قناتك هنا
      - key: M3U_MAX_CONCURRENCY_1
        value: "999999"
      - key: SYNC_ON_BOOT
        value: "true"
